const express=require('express');
const http=require('http');
const {Server}=require('socket.io');
const crypto=require('crypto');
const app=express();const server=http.createServer(app);const io=new Server(server);
app.use(express.static('public'));
const rooms=new Map();
const SUITS=['♠','♥','♦','♣'], RANKS=['2','3','4','5','6','7','8','9','10','J','Q','K','A'];
const newId=()=>crypto.randomUUID();
function roomCode(){let c;do{c=String(Math.floor(100000+Math.random()*900000));}while(rooms.has(c));return c;}
function newPlayer(socket,name){return {id:newId(),socketId:socket.id,name:String(name||'玩家').trim().slice(0,12)||'玩家',chips:1000,cards:[],out:false,reveal:false,seen:false,bet:0,totalBet:0,allIn:false,connected:true,trustee:false,timeLeft:20};}
function createRoom(socket,name){const room={code:roomCode(),players:[],phase:'waiting',round:0,turn:null,pot:0,requiredBet:20,previousBet:20,started:false,dealing:false,ended:false,compareMode:false,log:[],message:'等待另一位玩家加入',deck:[],timer:null,turnDeadline:0,showAllCards:false};rooms.set(room.code,room);join(room,socket,name);return room;}
function join(room,socket,name){if(room.players.length>=2)return null;const p=newPlayer(socket,name);room.players.push(p);socket.data.room=room.code;socket.data.player=p.id;socket.join(room.code);addLog(room,p.name+'进入房间');if(room.players.length===2){room.phase='playing';startRound(room);}broadcastRoomList();emitRoom(room);return p;}
function log(room,msg){room.log.unshift(msg);room.log=room.log.slice(0,45);room.message=msg;}
function shuffle(){const d=[];for(const s of SUITS)for(const r of RANKS)d.push({s,r});for(let i=d.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[d[i],d[j]]=[d[j],d[i]];}return d;}
function addLog(room,msg){log(room,msg);}
function publicState(room,pid){const slots=room.players.map((p,i)=>({id:p.id,slot:i===0?0:5,name:p.name,chips:p.chips,out:p.out,reveal:p.reveal||room.showAllCards,seen:p.seen,bet:p.bet,totalBet:p.totalBet,allIn:p.allIn,connected:p.connected,trustee:p.trustee,timeLeft:Math.max(0,Math.ceil((room.turnDeadline-Date.now())/1000)),cards:(p.id===pid||p.reveal||room.showAllCards)?p.cards:p.cards.map(()=>null)}));return {code:room.code,players:slots,me:pid,phase:room.phase,round:room.round,turnId:room.turn,pot:room.pot,requiredBet:room.requiredBet,previousBet:room.previousBet,started:room.started,dealing:room.dealing,ended:room.ended,compareMode:room.compareMode,log:room.log.slice(),message:room.message,showAllCards:room.showAllCards};}
function emitRoom(room){for(const p of room.players)if(p.socketId)io.to(p.socketId).emit('state',publicState(room,p.id));}
function broadcastRoomList(){const list=[...rooms.values()].filter(r=>r.players.length>0).map(r=>({code:r.code,count:r.players.filter(p=>p.connected).length,max:2,status:r.ended?'本局结束':r.started?'游戏中':r.players.length===1?'等待玩家':'等待中',canJoin:r.players.length<2&&!r.started,name:r.players[0]?.name||'公开房间'}));io.emit('roomList',list);}
function clearTimer(r){if(r.timer)clearTimeout(r.timer);r.timer=null;r.turnDeadline=0;}
function rank(cards){const vm={2:2,3:3,4:4,5:5,6:6,7:7,8:8,9:9,10:10,J:11,Q:12,K:13,A:14};const v=cards.map(c=>vm[c.r]).sort((a,b)=>b-a);const flush=cards.every(c=>c.s===cards[0].s);const counts={};v.forEach(x=>counts[x]=(counts[x]||0)+1);let sh=0;if(new Set(v).size===3){if(v[0]-v[1]===1&&v[1]-v[2]===1)sh=v[0];else if(v[0]===14&&v[1]===3&&v[2]===2)sh=3;}if(v[0]===v[2])return[6,v[0]];if(flush&&sh)return[5,sh];if(flush)return[4,...v];if(sh)return[3,sh];const pair=Object.keys(counts).map(Number).find(x=>counts[x]===2);if(pair!==undefined)return[2,pair,v.find(x=>x!==pair)];return[1,...v];}
function cmp(a,b){for(let i=0;i<Math.max(a.length,b.length);i++){const x=a[i]||0,y=b[i]||0;if(x>y)return 1;if(x<y)return -1;}return 0;}
function alive(r){return r.players.filter(p=>!p.out);}
function startTimer(r){clearTimer(r);if(r.ended||!r.started)return;const p=r.players.find(x=>x.id===r.turn);if(!p)return;r.turnDeadline=Date.now()+20000;r.timer=setTimeout(()=>{if(!r.ended&&r.turn===p.id&&!p.out){p.out=true;log(r,p.name+'超时，自动弃牌');finishIfNeeded(r);emitRoom(r);}},20000);}
function startRound(r){if(r.players.length!==2)return;clearTimer(r);r.round++;r.deck=shuffle();r.pot=0;r.requiredBet=20;r.previousBet=20;r.ended=false;r.started=true;r.dealing=false;r.phase='playing';r.compareMode=false;r.showAllCards=false;r.log=[];for(const p of r.players){p.cards=[];p.out=false;p.reveal=false;p.seen=false;p.bet=0;p.totalBet=20;p.allIn=false;p.trustee=false;p.chips=Math.max(0,p.chips-20);p.allIn=p.chips===0;r.pot+=20;}for(const p of r.players)for(let i=0;i<3;i++)p.cards.push(r.deck.pop());r.turn=r.players[Math.floor(Math.random()*2)].id;log(r,'第'+r.round+'局开始，双方各缴纳20底注并发牌；轮到 '+r.players.find(p=>p.id===r.turn).name);emitRoom(r);startTimer(r);broadcastRoomList();}
function finish(r){clearTimer(r);r.ended=true;r.started=true;r.phase='ended';r.compareMode=false;r.showAllCards=true;const levels=[...new Set(r.players.map(p=>p.totalBet||0).filter(v=>v>0))].sort((a,b)=>a-b);let prev=0;const payouts=new Map();const winnersAll=[];for(const level of levels){const contributors=r.players.filter(p=>(p.totalBet||0)>=level);const eligible=contributors.filter(p=>!p.out);const layer=(level-prev)*contributors.length;prev=level;if(layer<=0||!eligible.length)continue;let best=eligible[0],winners=[best];for(const p of eligible.slice(1)){const c=cmp(rank(p.cards),rank(best.cards));if(c>0){best=p;winners=[p];}else if(c===0)winners.push(p);}const each=Math.floor(layer/winners.length),rem=layer%winners.length;winners.forEach((p,i)=>{const amount=each+(i===0?rem:0);payouts.set(p.id,(payouts.get(p.id)||0)+amount);if(!winnersAll.includes(p))winnersAll.push(p);});}payouts.forEach((amount,id)=>{const p=r.players.find(x=>x.id===id);if(p)p.chips+=amount;});r.players.forEach(p=>p.reveal=true);const result=winnersAll.length?winnersAll.map(p=>p.name+'获得 '+(payouts.get(p.id)||0)+' 筹码').join('；'):'本局结束';log(r,'本局结束：'+result);emitRoom(r);broadcastRoomList();}
function finishIfNeeded(r){const a=alive(r);if(a.length<=1){finish(r);return;}const actionable=a.filter(p=>!p.allIn&&p.chips>0);if(actionable.length<=1){finish(r);return;}nextTurn(r);}
function nextTurn(r){clearTimer(r);if(r.ended)return;const a=alive(r),actionable=a.filter(p=>!p.allIn&&p.chips>0);if(a.length<=1||actionable.length<=1){finish(r);return;}const idx=r.players.findIndex(p=>p.id===r.turn);for(let k=1;k<=2;k++){const p=r.players[(idx+k)%2];if(!p.out&&!p.allIn&&p.chips>0){r.turn=p.id;break;}}r.compareMode=false;log(r,'轮到 '+r.players.find(p=>p.id===r.turn)?.name+' 操作');emitRoom(r);startTimer(r);}
function act(r,p,action,data={}){if(!r||!p)return;if(action==='restart'){if(r.players.length===2&&r.ended){r.players.forEach(x=>{x.chips=Math.max(1000,x.chips);});startRound(r);}return;}if(!r.started||r.ended||r.turn!==p.id||p.out||p.allIn)return;
 if(action==='look'){p.seen=true;log(r,p.name+'看牌');emitRoom(r);return;}
 if(action==='fold'){p.out=true;log(r,p.name+'弃牌');finishIfNeeded(r);emitRoom(r);return;}
 if(action==='trustee'){p.trustee=!p.trustee;log(r,p.name+(p.trustee?'开启托管':'取消托管'));emitRoom(r);if(p.trustee){setTimeout(()=>{if(!r.ended&&r.turn===p.id&&!p.out){act(r,p,'bet',{amount:Math.min(Math.max(r.requiredBet,20),p.chips)});}},450);}return;}
 if(action==='bet'){let amount=Number(data.amount);if(!Number.isInteger(amount)||amount<r.requiredBet||amount<=0)return;if(amount>p.chips)amount=p.chips;if(amount<=0)return;p.chips-=amount;p.bet=amount;p.totalBet+=amount;r.pot+=amount;p.allIn=p.chips===0;r.previousBet=amount;r.requiredBet=amount;log(r,p.name+'下注 '+amount+'，底池 '+r.pot+(p.allIn?'（全部投注）':''));finishIfNeeded(r);emitRoom(r);return;}
 if(action==='compare'){const target=r.players.find(x=>x.id===data.targetId||String(x.id)===String(data.targetId));if(!target||target.id===p.id||target.out)return;clearTimer(r);p.reveal=true;target.reveal=true;const c=cmp(rank(p.cards),rank(target.cards));if(c<0)p.out=true;else target.out=true;log(r,c>0?p.name+'比牌获胜':c<0?target.name+'比牌获胜':'比牌平手');finishIfNeeded(r);emitRoom(r);return;}}
function roomFor(s){return s.data.room?rooms.get(s.data.room):null;}
io.on('connection',socket=>{
 socket.emit('roomList',[...rooms.values()].map(r=>({code:r.code,count:r.players.filter(p=>p.connected).length,max:2,status:r.ended?'本局结束':r.started?'游戏中':'等待玩家',canJoin:r.players.length<2&&!r.started,name:r.players[0]?.name||'公开房间'})));
 socket.on('listRooms',()=>broadcastRoomList());
 socket.on('createRoom',({name}={})=>{if(roomFor(socket))return;const r=createRoom(socket,name);socket.emit('enteredRoom',{code:r.code});broadcastRoomList();emitRoom(r);});
 socket.on('quickMatch',({name}={})=>{if(roomFor(socket))return;let r=[...rooms.values()].find(x=>x.players.length===1&&!x.started&&x.players[0].connected);if(r){join(r,socket,name);socket.emit('enteredRoom',{code:r.code});}else{r=createRoom(socket,name);socket.emit('enteredRoom',{code:r.code});}broadcastRoomList();emitRoom(r);});
 socket.on('joinRoom',({code,name}={})=>{if(roomFor(socket))return;const r=rooms.get(String(code||'').trim());if(!r){socket.emit('errorMessage','房间不存在，请刷新大厅后重试。');return;}if(r.players.length>=2||r.started){socket.emit('errorMessage','房间已满或游戏已开始。');return;}join(r,socket,name);socket.emit('enteredRoom',{code:r.code});broadcastRoomList();emitRoom(r);});
 socket.on('action',({action,data}={})=>{const r=roomFor(socket);if(!r)return;const p=r.players.find(x=>x.id===socket.data.player);act(r,p,action,data||{});broadcastRoomList();});
 socket.on('disconnect',()=>{const r=roomFor(socket);if(!r)return;const p=r.players.find(x=>x.id===socket.data.player);if(p){p.connected=false;log(r,p.name+'连接中断');emitRoom(r);broadcastRoomList();setTimeout(()=>{if(r.players.every(x=>!x.connected)){clearTimer(r);rooms.delete(r.code);broadcastRoomList();}},120000);}});
});
const port=process.env.PORT||3000;server.listen(port,'0.0.0.0',()=>console.log('V28 public lobby listening on '+port));
