const express = require('express');
const http = require('http');
const { Server } = require('socket.io');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const accountFile = process.env.ACCOUNTS_FILE || path.join(process.cwd(), 'accounts.json');
let accounts = {};
try { accounts = JSON.parse(fs.readFileSync(accountFile, 'utf8')); } catch {}
function saveAccounts(){ try { fs.writeFileSync(accountFile, JSON.stringify(accounts, null, 2)); } catch(e) { console.error('Account save failed', e.message); }}
function passwordHash(password, salt=crypto.randomBytes(16).toString('hex')) { return { salt, hash: crypto.scryptSync(password, salt, 64).toString('hex') }; }
function safeName(v){ return String(v||'玩家').trim().slice(0,12) || '玩家'; }
const MAX_PLAYERS = 6;
function lobby(){ return [...rooms.values()].filter(r=>r.players.length<MAX_PLAYERS && !r.botRoom).map(r=>({code:r.code,players:r.players.length,maxPlayers:MAX_PLAYERS,host:r.players[0]?.name||'玩家',status:r.started&&!r.ended?'游戏中':'等待加入'})); }
const app = express(); const server = http.createServer(app); const io = new Server(server);
app.get('/health', (req,res)=>res.json({ok:true,version:'V29',rooms:rooms.size,uptime:Math.floor(process.uptime())}));
app.use(express.static('public'));
const rooms = new Map();
const suits=['♠','♥','♦','♣'], ranks=['2','3','4','5','6','7','8','9','10','J','Q','K','A'];
function code(){let s;do{s=String(Math.floor(100000+Math.random()*900000));}while(rooms.has(s));return s;}
function shuffledDeck(){const d=[];for(const s of suits)for(const r of ranks)d.push({s,r});for(let i=d.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[d[i],d[j]]=[d[j],d[i]];}return d;}
function freshPlayer(id,name,isBot=false){return {id,name:safeName(name),isBot,chips:1000,cards:[],out:false,reveal:false,seen:false,bet:0,totalBet:0,allIn:false,connected:true,trustee:false,timeLeft:20};}
function roomOf(socket){const c=socket.data.room;return c&&rooms.get(c);}
function publicState(room,forId){const ps=room.players.map(p=>({id:p.id,name:p.name,chips:p.chips,out:p.out,reveal:p.reveal||room.ended,seen:p.seen,bet:p.bet,totalBet:p.totalBet,allIn:p.allIn,connected:p.connected,trustee:p.trustee,isBot:!!p.isBot,timeLeft:p.timeLeft,cards:(p.id===forId||room.ended||p.reveal)?p.cards: p.cards.map(()=>null)}));return {code:room.code,players:ps,me:forId,phase:room.phase,round:room.round,turn:room.turn,pot:room.pot,requiredBet:room.requiredBet,previousBet:room.previousBet,started:room.started,dealing:room.dealing,ended:room.ended,compareMode:room.compareMode,log:room.log.slice(-35),message:room.message};}
function emitRoom(room){for(const p of room.players){if(p.socketId)io.to(p.socketId).emit('state',publicState(room,p.id));}}
function log(room,s){room.log.unshift(s);room.log=room.log.slice(0,60);room.message=s;}
function rank(cards){const vm={2:2,3:3,4:4,5:5,6:6,7:7,8:8,9:9,10:10,J:11,Q:12,K:13,A:14};const vals=cards.map(c=>vm[c.r]).sort((a,b)=>b-a);const flush=cards.every(c=>c.s===cards[0].s);const counts={};vals.forEach(v=>counts[v]=(counts[v]||0)+1);let sh=0;if(new Set(vals).size===3){if(vals[0]-vals[1]===1&&vals[1]-vals[2]===1)sh=vals[0];else if(vals[0]===14&&vals[1]===3&&vals[2]===2)sh=3;}if(vals[0]===vals[2])return [6,vals[0]];if(flush&&sh)return [5,sh];if(flush)return [4,...vals];if(sh)return [3,sh];const pair=Object.keys(counts).map(Number).find(v=>counts[v]===2);if(pair!==undefined)return [2,pair,vals.find(v=>v!==pair)];return [1,...vals];}
function cmp(a,b){const n=Math.max(a.length,b.length);for(let i=0;i<n;i++){if((a[i]||0)>(b[i]||0))return 1;if((a[i]||0)<(b[i]||0))return -1;}return 0;}
function alive(room){return room.players.filter(p=>!p.out);}
function clearTimer(room){if(room.timer)clearTimeout(room.timer);room.timer=null;}
function nextTurn(room){if(room.ended)return;const a=alive(room);if(a.length<=1){finish(room);return;}const current=room.players.findIndex(p=>p.id===room.turn);for(let k=1;k<=room.players.length;k++){const i=(current+k)%room.players.length,p=room.players[i];if(!p.out&&!p.allIn&&p.chips>0){room.turn=p.id;room.compareMode=false;p.timeLeft=20;log(room,'轮到 '+p.name+' 操作');emitRoom(room);startTurnTimer(room);return;}}finish(room);}
function startTurnTimer(room){clearTimer(room);const current=room.players.find(x=>x.id===room.turn); if(current?.isBot){room.timer=setTimeout(()=>botAct(room,current),700+Math.random()*900);return;} room.timer=setTimeout(()=>{const p=room.players.find(x=>x.id===room.turn);if(p&&!p.out&&!room.ended){p.out=true;log(room,p.name+'超时，自动弃牌');checkEnd(room);}},20000);}
function botAct(room,p){ if(!room || room.ended || room.turn!==p.id || p.out)return; const r=Math.random(); if(r<0.16 && room.players.filter(x=>!x.out).length>1){p.out=true;log(room,p.name+'弃牌');checkEnd(room);emitRoom(room);return;} if(r<0.34 && !p.seen){p.seen=true;log(room,p.name+'看牌');} const amount=Math.max(room.requiredBet,20); if(p.chips<=amount){room.pot+=p.chips;p.totalBet+=p.chips;p.bet=p.chips;p.chips=0;p.allIn=true;log(room,p.name+'全部投注');}else{p.chips-=amount;p.bet=amount;p.totalBet+=amount;room.pot+=amount;room.previousBet=amount;room.requiredBet=amount;log(room,p.name+'下注 '+amount);} checkEnd(room);emitRoom(room);}
function checkEnd(room){const a=alive(room);if(a.length<=1){finish(room);return;}const actionable=a.filter(p=>!p.allIn&&p.chips>0);if(actionable.length<=1){finish(room);return;}nextTurn(room);}
function finish(room){clearTimer(room);room.ended=true;room.phase='ended';room.started=true;room.compareMode=false;room.showAllCards=true;const a=alive(room);if(a.length){let best=a[0],winners=[best];for(const p of a.slice(1)){const c=cmp(rank(p.cards),rank(best.cards));if(c>0){best=p;winners=[p];}else if(c===0)winners.push(p);}const each=Math.floor(room.pot/winners.length),rem=room.pot%winners.length;winners.forEach((p,i)=>p.chips+=each+(i===0?rem:0));winners.forEach(p=>p.reveal=true);log(room,'本局结束：'+winners.map(p=>p.name).join('、')+'获胜，获得底池 '+room.pot+' 筹码');}else log(room,'本局结束');room.pot=0;emitRoom(room);}
function startRound(room){if(room.players.length<2||room.started&&!room.ended)return;clearTimer(room);room.round++;room.deck=shuffledDeck();room.pot=0;room.requiredBet=20;room.previousBet=20;room.ended=false;room.started=true;room.dealing=true;room.phase='playing';room.compareMode=false;room.showAllCards=false;room.log=[];for(const p of room.players){p.cards=[];p.out=false;p.reveal=false;p.seen=false;p.bet=0;p.totalBet=20;p.allIn=false;p.timeLeft=20;p.chips=Math.max(0,p.chips-20);room.pot+=20;}for(const p of room.players)for(let i=0;i<3;i++)p.cards.push(room.deck.pop());room.dealing=false;room.turn=room.players[Math.floor(Math.random()*room.players.length)].id;log(room,'第'+room.round+'局开始，双方各收到3张牌，底注20；轮到 '+room.players.find(p=>p.id===room.turn).name);emitRoom(room);startTurnTimer(room);}
function act(room,p,action,data={}){if(!room)return;if(action==='restart'){clearTimer(room);room.started=false;room.ended=false;room.phase='ready';room.pot=0;room.turn=null;room.compareMode=false;room.showAllCards=false;room.players.forEach(x=>{x.cards=[];x.out=false;x.reveal=false;x.seen=false;x.bet=0;x.totalBet=0;x.allIn=false;x.trustee=false;});log(room,'已重置，等待开始');emitRoom(room);return;}if(room.ended||room.dealing||!room.started||room.turn!==p.id||p.out||p.allIn)return;
 if(action==='look'){p.seen=true;log(room,p.name+'看牌');emitRoom(room);return;}
 if(action==='fold'){p.out=true;log(room,p.name+'弃牌');checkEnd(room);emitRoom(room);return;}
 if(action==='trustee'){p.trustee=!p.trustee;log(room,p.name+(p.trustee?'开启托管':'取消托管'));emitRoom(room);if(p.trustee){const amount=Math.min(Math.max(room.requiredBet,20),p.chips);if(amount>0){setTimeout(()=>{if(!room.ended&&room.turn===p.id&&!p.out){bet(room,p,amount);}},500);}}return;}
 if(action==='bet'){const amount=Number(data.amount);if(!Number.isInteger(amount)||amount<room.requiredBet||amount<=0)return;if(amount>=p.chips){p.totalBet+=p.chips;room.pot+=p.chips;p.chips=0;p.allIn=true;log(room,p.name+'筹码不足，已全部投注');}else{p.chips-=amount;p.totalBet+=amount;room.pot+=amount;log(room,p.name+'下注 '+amount+'，底池 '+room.pot);}p.bet=amount;room.previousBet=amount;room.requiredBet=amount;clearTimer(room);checkEnd(room);emitRoom(room);return;}
 if(action==='compare'){const target=room.players.find(x=>x.id===data.targetId);if(!target||target.id===p.id||target.out)return;clearTimer(room);p.reveal=true;target.reveal=true;const c=cmp(rank(p.cards),rank(target.cards));if(c<0)p.out=true;else target.out=true;log(room,c>0?p.name+'比牌获胜':c<0?target.name+'比牌获胜':'比牌平手');checkEnd(room);emitRoom(room);return;}
}
function bet(room,p,amount){act(room,p,'bet',{amount});}
io.on('connection',socket=>{
 socket.on('register',({username,password,name}={})=>{username=String(username||'').trim().toLowerCase();password=String(password||'');if(!/^[a-z0-9_]{3,20}$/.test(username)){socket.emit('authResult',{ok:false,message:'用户名需为3-20位字母、数字或下划线。'});return;}if(password.length<6||password.length>72){socket.emit('authResult',{ok:false,message:'密码长度需为6-72位。'});return;}if(accounts[username]){socket.emit('authResult',{ok:false,message:'用户名已存在，请直接登录。'});return;}const ph=passwordHash(password);accounts[username]={...ph,name:safeName(name||username),chips:1000,wins:0,games:0};saveAccounts();socket.data.user=username;socket.emit('authResult',{ok:true,username,name:accounts[username].name,chips:accounts[username].chips});socket.emit('lobbyRooms',lobby());});
 socket.on('login',({username,password}={})=>{username=String(username||'').trim().toLowerCase();const a=accounts[username];if(!a||passwordHashVerify(password,a)===false){socket.emit('authResult',{ok:false,message:'用户名或密码错误。'});return;}socket.data.user=username;socket.emit('authResult',{ok:true,username,name:a.name,chips:a.chips});socket.emit('lobbyRooms',lobby());});
 socket.on('lobbyRefresh',()=>socket.emit('lobbyRooms',lobby()));
 socket.on('logout',()=>{socket.data.user=null;});
 socket.on('createRoom',({name}={})=>{if(!socket.data.user){socket.emit('errorMessage','请先注册或登录。');return;} name=accounts[socket.data.user]?.name||name;const c=code(),p=freshPlayer(crypto.randomUUID(),name);p.socketId=socket.id;const room={code:c,players:[p],phase:'ready',round:0,turn:null,pot:0,requiredBet:20,previousBet:20,started:false,dealing:false,ended:false,compareMode:false,log:[],message:'房间已创建，等待另一位玩家加入。',timer:null};rooms.set(c,room);socket.data.room=c;socket.data.player=p.id;socket.emit('roomCreated',{code:c});emitRoom(room);io.emit('lobbyRooms',lobby());});
 socket.on('joinRoom',({code,name}={})=>{if(!socket.data.user){socket.emit('errorMessage','请先注册或登录。');return;} name=accounts[socket.data.user]?.name||name;const room=rooms.get(String(code||'').trim());if(!room){socket.emit('errorMessage','房间不存在，请检查6位房间号。');return;}if(room.players.length>=MAX_PLAYERS){socket.emit('errorMessage','房间已满，每桌最多6名玩家。');return;}const p=freshPlayer(crypto.randomUUID(),name);p.socketId=socket.id;room.players.push(p);socket.data.room=room.code;socket.data.player=p.id;log(room,p.name+'加入房间');socket.emit('roomJoined',{code:room.code});emitRoom(room);io.emit('lobbyRooms',lobby());});
 socket.on('addBot',()=>{const room=roomOf(socket);if(!room)return;if(!socket.data.user){socket.emit('errorMessage','请先登录。');return;}if(room.players.length>=MAX_PLAYERS){socket.emit('errorMessage','房间已满，每桌最多6名玩家。');return;}const bot=freshPlayer('bot-'+crypto.randomUUID(),['机器人小虎机器人','AI小王','牌神阿强','智能玩家'][Math.floor(Math.random()*4)],true);room.players.push(bot);log(room,bot.name+'加入房间');emitRoom(room);socket.emit('botAdded',{code:room.code});socket.emit('lobbyRooms',lobby());});
 socket.on('startRound',()=>{const room=roomOf(socket);if(!room)return;if(room.players.length<2){socket.emit('errorMessage','请等待另一位玩家加入后再开始。');return;}if(!room.started||room.ended)startRound(room);});
 socket.on('action',({action,data}={})=>{const room=roomOf(socket);if(!room)return;const p=room.players.find(x=>x.id===socket.data.player);if(!p)return;if(action==='restart'){act(room,p,action,data);return;}act(room,p,action,data);});
 socket.on('disconnect',()=>{const room=roomOf(socket);if(!room)return;const p=room.players.find(x=>x.id===socket.data.player);if(p){p.connected=false;log(room,p.name+'连接中断');emitRoom(room);}});
});
function passwordHashVerify(password,a){try{return crypto.timingSafeEqual(Buffer.from(passwordHash(String(password||''),a.salt).hash,'hex'),Buffer.from(a.hash,'hex'));}catch{return false;}}
const port=process.env.PORT||3000;server.listen(port,'0.0.0.0',()=>console.log('ZhaJinHua V29 online server listening on '+port));
